### ISSUE TITLE
Build Failed on Linux/ARMv7

### ISSUE THREAD

**Issue by ZihengJiang** [Maratyszcza/NNPACK#87]
Hi, I tried to follow the instruction to build NNPack on ARM. But `ninja` failed with error. Could you help me find what is wrong? Thank you!

Here is the log:

```
[1/154] CC src/init.c
[2/154] CC src/fully-connected-output.c
[3/154] CC src/fully-connected-inference.c
[4/154] CC src/convolution-kernel-gradient.c
[5/154] CC src/convolution-input-gradient.c
[6/154] CC src/convolution-output.c
[7/154] CC src/pooling-output.c
[8/154] CC src/softmax-output.c
[9/154] CC src/relu-input-gradient.c
[10/154] CC src/relu-output.c
[11/154] CC src/psimd/relu.c
[12/154] CC src/convolution-inference.c
[13/154] CC src/psimd/fft-block-mac.c
[14/154] CC src/neon/blas/c4gemm.c
FAILED: /home/joe/projects/NNPACK/build/src/neon/blas/c4gemm.c.o 
gcc -o /home/joe/projects/NNPACK/build/src/neon/blas/c4gemm.c.o -c /home/joe/projects/NNPACK/src/neon/blas/c4gemm.c -MMD -MF /home/joe/projects/NNPACK/build/src/neon/blas/c4gemm.c.o.d -O2 -march=armv7-a -mfpu=neon -std=gnu99 -g -pthread   -I/home/joe/projects/NNPACK/include -I/home/joe/projects/NNPACK/src -I/home/joe/projects/NNPACK/src/ref -I/home/joe/projects/NNPACK/deps/psimd/include -I/home/joe/projects/NNPACK/deps/pthreadpool/include -I/home/joe/projects/NNPACK/deps/fxdiv/include -I/home/joe/projects/NNPACK/deps/fp16/include
In file included from /home/joe/projects/NNPACK/src/neon/blas/c4gemm.c:4:0:
/home/joe/projects/NNPACK/include/nnpack/arm_neon.h: In function ‘vld1q_f32_f16’:
/home/joe/projects/NNPACK/include/nnpack/arm_neon.h:45:3: warning: implicit declaration of function ‘vcvt_f32_f16’ [-Wimplicit-function-declaration]
   return vcvt_f32_f16((float16x4_t) vld1_u16((const uint16_t*) address));
   ^
/home/joe/projects/NNPACK/include/nnpack/arm_neon.h:45:3: error: incompatible types when returning type ‘int’ but ‘float32x4_t’ was expected
/home/joe/projects/NNPACK/include/nnpack/arm_neon.h: In function ‘vld1q_f32_f16_aligned’:
/home/joe/projects/NNPACK/include/nnpack/arm_neon.h:49:3: error: incompatible types when returning type ‘int’ but ‘float32x4_t’ was expected
   return vcvt_f32_f16((float16x4_t)
   ^
/home/joe/projects/NNPACK/include/nnpack/arm_neon.h: In function ‘vst1q_f16_f32’:
/home/joe/projects/NNPACK/include/nnpack/arm_neon.h:54:3: warning: implicit declaration of function ‘vcvt_f16_f32’ [-Wimplicit-function-declaration]
   vst1_u16((uint16_t*) address, (uint16x4_t) vcvt_f16_f32(address));
   ^
/home/joe/projects/NNPACK/include/nnpack/arm_neon.h:54:3: error: can’t convert between vector values of different size
/home/joe/projects/NNPACK/include/nnpack/arm_neon.h: In function ‘vst1q_f16_f32_aligned’:
/home/joe/projects/NNPACK/include/nnpack/arm_neon.h:59:4: error: can’t convert between vector values of different size
    (uint16x4_t) vcvt_f16_f32(address));
    ^
[15/154] CC src/neon/blas/s4gemm.c
FAILED: /home/joe/projects/NNPACK/build/src/neon/blas/s4gemm.c.o 
gcc -o /home/joe/projects/NNPACK/build/src/neon/blas/s4gemm.c.o -c /home/joe/projects/NNPACK/src/neon/blas/s4gemm.c -MMD -MF /home/joe/projects/NNPACK/build/src/neon/blas/s4gemm.c.o.d -O2 -march=armv7-a -mfpu=neon -std=gnu99 -g -pthread   -I/home/joe/projects/NNPACK/include -I/home/joe/projects/NNPACK/src -I/home/joe/projects/NNPACK/src/ref -I/home/joe/projects/NNPACK/deps/psimd/include -I/home/joe/projects/NNPACK/deps/pthreadpool/include -I/home/joe/projects/NNPACK/deps/fxdiv/include -I/home/joe/projects/NNPACK/deps/fp16/include
In file included from /home/joe/projects/NNPACK/src/neon/blas/s4gemm.c:4:0:
/home/joe/projects/NNPACK/include/nnpack/arm_neon.h: In function ‘vld1q_f32_f16’:
/home/joe/projects/NNPACK/include/nnpack/arm_neon.h:45:3: warning: implicit declaration of function ‘vcvt_f32_f16’ [-Wimplicit-function-declaration]
   return vcvt_f32_f16((float16x4_t) vld1_u16((const uint16_t*) address));
   ^
/home/joe/projects/NNPACK/include/nnpack/arm_neon.h:45:3: error: incompatible types when returning type ‘int’ but ‘float32x4_t’ was expected
/home/joe/projects/NNPACK/include/nnpack/arm_neon.h: In function ‘vld1q_f32_f16_aligned’:
/home/joe/projects/NNPACK/include/nnpack/arm_neon.h:49:3: error: incompatible types when returning type ‘int’ but ‘float32x4_t’ was expected
   return vcvt_f32_f16((float16x4_t)
   ^
/home/joe/projects/NNPACK/include/nnpack/arm_neon.h: In function ‘vst1q_f16_f32’:
/home/joe/projects/NNPACK/include/nnpack/arm_neon.h:54:3: warning: implicit declaration of function ‘vcvt_f16_f32’ [-Wimplicit-function-declaration]
   vst1_u16((uint16_t*) address, (uint16x4_t) vcvt_f16_f32(address));
   ^
/home/joe/projects/NNPACK/include/nnpack/arm_neon.h:54:3: error: can’t convert between vector values of different size
/home/joe/projects/NNPACK/include/nnpack/arm_neon.h: In function ‘vst1q_f16_f32_aligned’:
/home/joe/projects/NNPACK/include/nnpack/arm_neon.h:59:4: error: can’t convert between vector values of different size
    (uint16x4_t) vcvt_f16_f32(address));
    ^
[16/154] CC src/psimd/softmax.c
[17/154] CC src/psimd/2d-winograd-8x8-3x3.c
[18/154] CC src/psimd/2d-fourier-8x8.c
[19/154] CC src/psimd/2d-fourier-16x16.c
ninja: build stopped: subcommand failed.

```

**Comment by Maratyszcza** [comment]
I think the problem is caused by commit 689936cb4f8982cfe0a9a8ff487b312d2e9cb4fa. I'll fix it later this week, and in the mean time you can checkout 748b9e18cfe3749aa14cd67d85dedeb74459fd7d which should build fine.

**Comment by ZihengJiang** [comment]
Thanks for your reply, `748b9e1` still has some build issues. Finally, I choose `02bf347` for my task. Hope CI will be added to detect build status.

**Comment by knsong** [comment]
@Maratyszcza  I followed the building instructions as `Cross-compilation for Android` wiki on `2695759` , but also got the similar errors like 'jni/../include/nnpack/arm_neon.h:26:10: error: returning 'int' from a function with incompatible result type 'float32x4_t''. ps I used `android-ndk-r14-beta1` and `android-21`.

**Comment by Maratyszcza** [comment]
@knsong This should be fixed with 3627062907e01ba5f030730f1027dd773323e0e3

**Comment by knsong** [comment]
@Maratyszcza Thanks. `3627062` builded with no problem.
